export const FirstNameError = 'First name is too long.'
export const LastNameErrorLength = 'Last name is too long.'
export const LastNameExsistanceError = 'Last name is required'
export const PhoneNumberError = 'Please enter valid phone number.'
export const EmailError = 'Please enter valid email'
export const NotesLengthError = 'At list singe note required'
export const AddressError = 'At list singe address required'
export const PurchaseError = "Purchase amount can't be negative"
export const LastPurchaseDateError = 'Last purchase date too low'
